server:
  port: 8097

eureka:
  client:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cms_licenses_db
    username: chemical
    password: chemical
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/chemical-management
  kafka:
    bootstrap-servers: localhost:9092
